sudo: false
repo_token: Yt71K1wQ83RTyiSxvVwkgnrYng9rQTFQn
language: node_js
node_js:
  - stable
  - 6
  - 4
script: 
  - npm test
after_script: "npm install coveralls && cd test-cov &&  cat coverage.lcov | ../node_modules/coveralls/bin/coveralls.js && cd .. && rm -rf ./test-cov && rm -rf ./test-app"